import type { Activity, ActivityType, Deadline, DeadlineKind, Investor, InvestorTier, Project, TokenSlice } from "./types";
import { SLICE_PALETTE } from "./types";

const day = (offset: number) => new Date(Date.now() + offset * 86400000).toISOString().slice(0, 10);
const created = (daysAgo: number) => Date.now() - daysAgo * 86400000;

let n = 0;
const A = (title: string, type: ActivityType, opts: Partial<Activity> = {}): Activity => ({
  id: `act-${++n}`,
  title,
  type,
  dailyReset: false,
  done: false,
  ...opts,
});
const I = (name: string, tier: InvestorTier, amountUsd?: number, roundDate?: string): Investor => ({
  id: `inv-${++n}`,
  name,
  tier,
  amountUsd,
  roundDate,
});
const D = (date: string, kind: DeadlineKind, title: string): Deadline => ({ id: `dl-${++n}`, date, kind, title });
const S = (label: string, value: number, idx: number): TokenSlice => ({
  id: `ts-${++n}`,
  label,
  value,
  color: SLICE_PALETTE[idx % SLICE_PALETTE.length],
});

export function seedProjects(): Project[] {
  return [
    {
      id: "p-monad",
      name: "Monad",
      ticker: "MON",
      website: "https://monad.xyz",
      description:
        "Высокопроизводительная EVM-совместимая L1 с параллельным исполнением транзакций и заявленной пропускной способностью 10 000 TPS. Тестнет активно поощряет ончейн-активность, а сообщество Monad — одно из самых живых в цикле.",
      categories: ["L1", "Инфраструктура"],
      tags: ["parallel-evm", "testnet", "high-tps", "paradigm"],
      status: "registration",
      rewardTypes: ["airdrop", "points", "discord"],
      blockchain: "Своя L1",
      priority: "high",
      difficulty: "medium",
      claimUrl: "",
      deadlines: [
        D(day(5), "registration", "Закрытие регистрации в тестнете"),
        D(day(12), "snapshot", "Снапшот тестнет-активности"),
        D(day(34), "claim", "Ожидаемое TGE и клейм"),
      ],
      activities: [
        A("Забрать токены из крана (faucet)", "daily", { dailyReset: true, done: true, url: "https://testnet.monad.xyz" }),
        A("Выполнить свапы на DEX тестнета", "testnet", { done: true, url: "https://testnet.monad.xyz" }),
        A("Задеплоить смарт-контракт", "testnet", { done: false }),
        A("Минтить NFT-бейджи экосистемы", "testnet", { done: true }),
        A("Пройти верификацию профиля (Galxe)", "social", { done: true, url: "https://galxe.com" }),
        A("Ежедневные квесты Nads Daily", "daily", { dailyReset: true, done: false, url: "https://monad.xyz" }),
        A("Привести 3 рефералов", "referral", { done: false }),
      ],
      investors: [
        I("Paradigm", 1, 225_000_000, "2024-04-09"),
        I("Electric Capital", 1, undefined, "2024-04-09"),
        I("Greenoaks Capital", 2, undefined, "2023-08-01"),
      ],
      tokenStandard: "Native (ERC-20-совместимый)",
      totalSupply: "10 000 000 000 MON",
      tokenomics: [
        S("Комьюнити и аирдроп", 40, 0),
        S("Инвесторы", 24.5, 1),
        S("Команда", 19.5, 2),
        S("Экосистема", 16, 3),
      ],
      createdAt: created(41),
    },
    {
      id: "p-bera",
      name: "Berachain",
      ticker: "BERA",
      website: "https://berachain.com",
      description:
        "L1 на Cosmos SDK с новой моделью консенсуса Proof-of-Liquidity. Экосистема строится вокруг культовой мем-культуры медведей и трёх нативных токенов: BERA, BGT и HONEY.",
      categories: ["L1", "DeFi"],
      tags: ["proof-of-liquidity", "cosmos", "memecoin"],
      status: "completed",
      rewardTypes: ["airdrop", "nft"],
      blockchain: "Своя L1",
      priority: "low",
      difficulty: "easy",
      claimUrl: "https://claim.berachain.com",
      deadlines: [D(day(-12), "claim", "Клейм BERA завершён")],
      activities: [
        A("Клейм BERA за тестнет-активность", "mainnet", { done: true, url: "https://claim.berachain.com" }),
        A("Минт NFT Bongo", "other", { done: true }),
        A("Стейкинг BGT у валидаторов", "staking", { done: true }),
      ],
      investors: [
        I("Framework Ventures", 1, 142_000_000, "2024-04-25"),
        I("Polychain Capital", 1, undefined, "2023-02-14"),
        I("Hack VC", 2, undefined, "2023-02-14"),
      ],
      tokenStandard: "Native / ERC-20",
      totalSupply: "500 000 000 BERA",
      tokenomics: [
        S("Комьюнити", 49.6, 0),
        S("Инвесторы", 23, 1),
        S("Контрибьюторы", 21.4, 2),
        S("Экосистема", 6, 3),
      ],
      createdAt: created(120),
    },
    {
      id: "p-eclipse",
      name: "Eclipse",
      ticker: "ES",
      website: "https://eclipse.xyz",
      description:
        "Первая L2 на Ethereum, исполняющая программы Solana Virtual Machine. Совмещает скорость SVM с безопасностью Ethereum и доступностью данных Celestia.",
      categories: ["L2", "Инфраструктура"],
      tags: ["svm", "ethereum-l2", "celestia"],
      status: "confirmed",
      rewardTypes: ["airdrop", "points"],
      blockchain: "Ethereum",
      priority: "high",
      difficulty: "medium",
      claimUrl: "",
      deadlines: [
        D(day(3), "snapshot", "Снапшот второго сезона поинтов"),
        D(day(21), "claim", "Клейм токена ES"),
      ],
      activities: [
        A("Бридж ETH в сеть Eclipse", "mainnet", { done: true, url: "https://bridge.eclipse.xyz" }),
        A("Торговля на DEX-агрегаторах", "trading", { done: true }),
        A("Предоставление ликвидности", "liquidity", { done: false }),
        A("Дейли-чек-ин в приложении", "daily", { dailyReset: true, done: true, url: "https://eclipse.xyz" }),
        A("Участие в программе лояльности", "other", { done: false }),
      ],
      investors: [
        I("Polychain Capital", 1, 50_000_000, "2024-01-30"),
        I("Hack VC", 2, undefined, "2024-01-30"),
        I("Tabiya", 2, undefined, "2023-06-15"),
      ],
      tokenStandard: "SPL / ERC-20",
      totalSupply: "1 000 000 000 ES",
      tokenomics: [
        S("Комьюнити", 30, 0),
        S("Инвесторы", 26, 1),
        S("Команда", 22, 2),
        S("Экосистема", 12, 3),
        S("Резерв", 10, 4),
      ],
      createdAt: created(87),
    },
    {
      id: "p-sonic",
      name: "Sonic",
      ticker: "S",
      website: "https://soniclabs.com",
      description:
        "Ребрендинг Fantom: самая быстрая EVM-сеть с финализацией за секунду. Программа Points to Gems конвертирует активность пользователей в токены S.",
      categories: ["L1", "DEX", "DeFi"],
      tags: ["fantom", "airdrop-live", "gems"],
      status: "claiming",
      rewardTypes: ["airdrop", "points"],
      blockchain: "Своя L1",
      priority: "high",
      difficulty: "easy",
      claimUrl: "https://airdrop.soniclabs.com",
      deadlines: [
        D(day(2), "claim", "Волна 4: клейм открыт"),
        D(day(9), "registration", "Регистрация в Points to Gems S2"),
      ],
      activities: [
        A("Клейм S за Gems (волна 4)", "mainnet", { done: false, url: "https://airdrop.soniclabs.com" }),
        A("Свапы на SwapX", "trading", { done: true, url: "https://swapx.fi" }),
        A("Стейкинг S у валидаторов", "staking", { done: false }),
        A("Ежедневный сбор Gems", "daily", { dailyReset: true, done: true, url: "https://points.soniclabs.com" }),
        A("LP в пулах Silo Finance", "liquidity", { done: false }),
      ],
      investors: [I("Fantom Foundation", 1, 40_000_000, "2024-09-12")],
      tokenStandard: "Native / ERC-20",
      totalSupply: "2 099 000 000 S",
      tokenomics: [
        S("Комьюнити и экосистема", 38, 0),
        S("Инвесторы", 24, 1),
        S("Команда", 20, 2),
        S("Фонд развития", 18, 3),
      ],
      createdAt: created(60),
    },
    {
      id: "p-fuel",
      name: "Fuel Network",
      ticker: "FUEL",
      website: "https://fuel.network",
      description:
        "Модульный экзекшн-слой с параллельной виртуальной машиной FuelVM и языком Sway. Сезон поинтов завершается — ожидается конвертация в токен FUEL.",
      categories: ["L2", "Инфраструктура"],
      tags: ["modular", "svm", "sway"],
      status: "registration",
      rewardTypes: ["airdrop", "points", "wl"],
      blockchain: "Ethereum",
      priority: "medium",
      difficulty: "hard",
      claimUrl: "",
      deadlines: [
        D(day(4), "registration", "Онбординг Sway-разработчиков"),
        D(day(17), "snapshot", "Финальный снапшот поинтов"),
      ],
      activities: [
        A("Бридж активов через Fuel Bridge", "mainnet", { done: true, url: "https://app.fuel.network" }),
        A("Деплой контракта на Sway", "testnet", { done: false, url: "https://fuel.network" }),
        A("Торговля на Spark", "trading", { done: false }),
        A("Ежедневные миссии Season 2", "daily", { dailyReset: true, done: false, url: "https://app.fuel.network" }),
        A("Социальные квесты", "social", { done: true }),
      ],
      investors: [
        I("Blockchain Capital", 1, 80_000_000, "2024-01-10"),
        I("Stratos", 2, undefined, "2022-09-22"),
        I("Fenbushi Capital", 2, undefined, "2022-09-22"),
      ],
      tokenStandard: "Native Fuel",
      totalSupply: "1 000 000 000 FUEL",
      tokenomics: [
        S("Экосистема", 35, 0),
        S("Инвесторы", 25, 1),
        S("Команда", 25, 2),
        S("Комьюнити", 15, 3),
      ],
      createdAt: created(33),
    },
    {
      id: "p-linea",
      name: "Linea",
      ticker: "LINEA",
      website: "https://linea.build",
      description:
        "zkEVM-сеть от ConsenSys с интеграцией MetaMask. Программа Linea Surge распределяет LXP и LXP-L поинты за ликвидность — токен ожидается после финального сезона.",
      categories: ["L2", "zkEVM"],
      tags: ["zkevm", "consensys", "metamask", "lxp"],
      status: "potential",
      rewardTypes: ["airdrop", "points"],
      blockchain: "Ethereum",
      priority: "medium",
      difficulty: "medium",
      claimUrl: "",
      deadlines: [D(day(27), "snapshot", "Завершение Linea Surge S3")],
      activities: [
        A("Минт Linea Profile NFT", "mainnet", { done: true, url: "https://linea.build" }),
        A("Объём торгов на DEX сети", "trading", { done: false }),
        A("Ликвидность в протоколах-партнёрах", "liquidity", { done: false, url: "https://linea.build" }),
        A("Активность в MetaMask Portfolio", "other", { done: true }),
      ],
      investors: [I("ConsenSys", 1, 725_000_000, "2023-04-27"), I("ParaFi Capital", 2, undefined, "2023-04-27")],
      tokenStandard: "ERC-20 (ожидается)",
      totalSupply: "Не объявлен",
      tokenomics: [
        S("Экосистема", 40.4, 0),
        S("Инвесторы", 29.6, 1),
        S("Команда", 20, 2),
        S("Комьюнити", 10, 3),
      ],
      createdAt: created(25),
    },
    {
      id: "p-plume",
      name: "Plume Network",
      ticker: "PLUME",
      website: "https://plumenetwork.xyz",
      description:
        "Первая L1 для RWAfi: токенизация реальных активов с комплаенсом на уровне протокола. Клейм сезона миль открыт для ранних пользователей.",
      categories: ["L1", "RWA"],
      tags: ["rwa", "tokenization", "claim-live"],
      status: "claiming",
      rewardTypes: ["airdrop", "nft"],
      blockchain: "Своя L1",
      priority: "medium",
      difficulty: "easy",
      claimUrl: "https://claim.plumenetwork.xyz",
      deadlines: [
        D(day(6), "claim", "Клейм миль за сезон 1"),
        D(day(20), "snapshot", "Снапшот RWA-активности S2"),
      ],
      activities: [
        A("Клейм PLUME за мили", "mainnet", { done: true, url: "https://claim.plumenetwork.xyz" }),
        A("Минт RWA-активов на тестовых рынках", "other", { done: true, url: "https://plumenetwork.xyz" }),
        A("Стейкинг PLUME", "staking", { done: false }),
        A("Реферальная программа", "referral", { done: false }),
      ],
      investors: [I("Haun Ventures", 1, 20_000_000, "2024-03-14"), I("Galaxy Ventures", 2, undefined, "2024-03-14")],
      tokenStandard: "ERC-20",
      totalSupply: "10 000 000 000 PLUME",
      tokenomics: [
        S("Комьюнити", 37, 0),
        S("Экосистема", 25, 1),
        S("Инвесторы", 23, 2),
        S("Команда", 15, 3),
      ],
      createdAt: created(18),
    },
    {
      id: "p-hyperliquid",
      name: "Hyperliquid",
      ticker: "HYPE",
      website: "https://hyperliquid.xyz",
      description:
        "Самая ликвидная децентрализованная перп-биржа на собственном L1. Уникальна полным отсутствием венчурных инвесторов — 31% токенов распределено сообществу.",
      categories: ["DEX", "DeFi"],
      tags: ["perps", "no-vc", "points-done"],
      status: "completed",
      rewardTypes: ["airdrop"],
      blockchain: "Своя L1",
      priority: "low",
      difficulty: "hard",
      claimUrl: "https://app.hyperliquid.xyz",
      deadlines: [],
      activities: [
        A("Клейм HYPE (сезон 1)", "mainnet", { done: true, url: "https://app.hyperliquid.xyz" }),
        A("Торговля перпами в тестнете", "trading", { done: true }),
      ],
      investors: [],
      tokenStandard: "Native HYPE",
      totalSupply: "1 000 000 000 HYPE",
      tokenomics: [
        S("Комьюнити (ретро)", 31, 0),
        S("Будущие раздачи", 23.8, 1),
        S("Команда", 23.8, 2),
        S("Фонд", 21.4, 3),
      ],
      createdAt: created(150),
    },
    {
      id: "p-initia",
      name: "Initia",
      ticker: "INIT",
      website: "https://initia.xyz",
      description:
        "Сеть для взаимосвязанных роллапов Minitia на Move. Программа The Initiation завершена, токен подтверждён к листингу на крупных биржах.",
      categories: ["L1", "Инфраструктура"],
      tags: ["move", "rollups", "binance-labs"],
      status: "confirmed",
      rewardTypes: ["airdrop", "points"],
      blockchain: "Move",
      priority: "medium",
      difficulty: "medium",
      claimUrl: "https://initia.xyz/init",
      deadlines: [
        D(day(8), "claim", "Открытие клейма INIT"),
        D(day(15), "other", "Листинг на биржах"),
      ],
      activities: [
        A("Клейм INIT за The Initiation", "mainnet", { done: false, url: "https://initia.xyz/init" }),
        A("Делегирование TIA/ALT", "staking", { done: true }),
        A("Активность на тестнете Minitia", "testnet", { done: true }),
        A("Квесты Galxe и Zealy", "social", { done: true }),
        A("Ежедневные задания Initia app", "daily", { dailyReset: true, done: false, url: "https://initia.xyz" }),
      ],
      investors: [
        I("Binance Labs", 1, 45_000_000, "2024-02-20"),
        I("Delphi Ventures", 1, undefined, "2024-02-20"),
        I("Hack VC", 2, undefined, "2023-10-05"),
      ],
      tokenStandard: "Native INIT",
      totalSupply: "10 000 000 000 INIT",
      tokenomics: [
        S("Комьюнити", 30, 0),
        S("Экосистема", 25, 1),
        S("Инвесторы", 25, 2),
        S("Команда", 20, 3),
      ],
      createdAt: created(52),
    },
    {
      id: "p-abstract",
      name: "Abstract",
      ticker: "ABS",
      website: "https://abs.xyz",
      description:
        "Consumer-L2 от команды Pudgy Penguins на стеке zkSync. Фокус на потребительских приложениях, культуре и геймификации онбординга.",
      categories: ["L2", "Социалки", "Игры"],
      tags: ["consumer", "pudgy", "zksync-stack"],
      status: "potential",
      rewardTypes: ["points", "nft", "wl"],
      blockchain: "zkEVM",
      priority: "high",
      difficulty: "easy",
      claimUrl: "",
      deadlines: [
        D(day(11), "registration", "Регистрация Abstract Global Wallet"),
        D(day(29), "snapshot", "Снапшот поинтов Badger"),
      ],
      activities: [
        A("Создать Abstract Global Wallet", "mainnet", { done: true, url: "https://abs.xyz" }),
        A("Минт NFT Badges", "other", { done: true, url: "https://abs.xyz" }),
        A("Играть в мини-приложения сети", "other", { done: false }),
        A("Ежедневные Badger-квесты", "daily", { dailyReset: true, done: true, url: "https://abs.xyz" }),
        A("Пригласить друзей по рефкоду", "referral", { done: false }),
      ],
      investors: [I("Founders Fund", 1, 260_000_000, "2024-11-27"), I("Fenbushi Capital", 2, undefined, "2024-11-27")],
      tokenStandard: "ERC-20 (ожидается)",
      totalSupply: "Не объявлен",
      tokenomics: [
        S("Экосистема", 42, 0),
        S("Команда", 27.5, 1),
        S("Инвесторы", 20.5, 2),
        S("Комьюнити", 10, 3),
      ],
      createdAt: created(9),
    },
  ];
}
